name: Sync to Remote Repository

on:
  push:
    branches:
      - main

jobs:
  copy-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        repository: AdoptaUnJuniorPlatform/GT-PodcastParty
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - name: Set up Git
      run: |
        git config user.name "PMFrancisco"
        git config user.email "francisco.perez.munoz@gmail.com"

    - name: Mirror to target repository
      run: |
        git remote add destination https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/PMFrancisco/clon-podcastParty.git
        git push destination main --force
        


