name: Sync to Remote Repository

on:
  push:
    branches:
      - main

jobs:
  copy-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: sator-imaging/Copy-to-Another-Repository@v1
        with:
          target-filepath: './'
          output-branch: 'main'
          output-repo: 'PMFrancisco/clon-podcastParty'
          git-token: ${{ secrets.API_TOKEN_GITHUB }}
          commit-message-prefix: '[Sync] '
          output-directory: './'
          pr-branch-prefix: "sync/"
          pr-title: "Sincronización automática"
          pr-message: "Sincronización desde el repositorio original"
          git-name: "PMFrancisco"
          git-email: 'francisco.perez.munoz@gmail.com'
